### ISSUE TITLE
Generate themed screenshots

### ISSUE THREAD

**Issue by kearabiloe** [proversity-org/edx-app-android#17]
Provide login credentials to Device farm in-app explorer, and save generated screenshots in a meta  folder

**Comment by renevatium** [comment]
Keep working on this as an automation process. I'll get the initial screenshots up for beta

**Comment by kearabiloe** [comment]
@renevatium Cool, will be generating future screenshots in [this](https://github.com/proversity-org/edx-app-android/issues/18) pre push hook

**Comment by kearabiloe** [comment]
Duplicate of #64
