### ISSUE TITLE
Discover Parse alternative

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-android#27]
Research alternative to Parse for push notifications in mobile apps.

**Comment by jagonzalr** [comment]
Mixpanel, expensive ($150 per month): https://mixpanel.com/

**Comment by jagonzalr** [comment]
Batch is a free alternative: https://batch.com

**Comment by jagonzalr** [comment]
Boxcar is a 7 euro alternative (https://boxcar.io)
