### ISSUE TITLE
Test on AWS Device farm

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-android#41]
Deploy via AWS mobile hub

**Comment by renevatium** [comment]
What are the financial requirements here? ie How many free deploys/tests etc do we get?

**Comment by kearabiloe** [comment]
@renevatium 
Device farm:
Billed per device minute == number of devices + tests duration
First 250 device minutes free
$0.17 per device minute

**Comment by renevatium** [comment]
Thank you. Please keep track of minutes accrued and log here

**Comment by kearabiloe** [comment]
Cool. Device farm now at: 73.900 Minutes
