### ISSUE TITLE
Android deployment - Jenkins on EC2

### ISSUE THREAD

**Issue by kearabiloe** [proversity-org/edx-app-android#44]

**Comment by renevatium** [comment]
Can I get an idea of progress here please? What steps are working/missing etc?

**Comment by kearabiloe** [comment]
1. Android SDK, Jenkins + dependencies on EC2 (DONE)
2. Test on Device Farm (In progress)
3. Publish to Play Store (To Do)
4. Housekeeping {build notifications, Git branch filters etc} (To DO)

**Comment by renevatium** [comment]
Cool. Taken quite a while to get this far. Need to move on soon. Please have demo of process ready for tomorrow.

**Comment by renevatium** [comment]
Please link the tutorial used for this build system for future reference

**Comment by kearabiloe** [comment]
@renevatium didn't use a tutorial for the build, just followed Jenkins installation instruction and added plugins. 
1. Install jenkins https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu
2. Install the Android SDK 
3. Install and configure the following jenkins plugins:
4. aws-device-farm
5. GitHub 
6. Configure your project: set android environment paths, Git polling, Device farm

**Comment by kearabiloe** [comment]
public url: http://ec2-52-37-229-107.us-west-2.compute.amazonaws.com:8080/
username: admin
password: Pr0ver$ity
