### ISSUE TITLE
Move to Larger Box: Jenkins Deployment

### ISSUE THREAD

**Issue by kearabiloe** [proversity-org/edx-app-android#50]

**Comment by renevatium** [comment]
Update to at the very least a t2 instance (Preferably medium/large) and test for build time difference.

**Comment by renevatium** [comment]
This was discussed yesterday and has not been done.

**Comment by renevatium** [comment]
Please tag (name) the new instance as _android.proversity.org_ (in keeping with tagging convention)

**Comment by renevatium** [comment]
Should be a quick build. Please log test times on Samsung S7 vs times on small box by end of day.

**Comment by renevatium** [comment]
Waiting for information regarding difference in build/test times. Is a bigger box necessary?

**Comment by kearabiloe** [comment]
Build times(jenkins-->Device farm-->Play store):
T2.large: 1 h 32 
M3.medium : 1 h 20 
The M3 instance was already terminated, that is a rough estimation of what I recall. Is it worth moving to a bigger box for Android/Jenkins deployments? No, There’s not much of a difference in terms of build times and storage

**Comment by renevatium** [comment]
Awesome, that's useful info. Strange that the Jenkins build time is about the same on a larger box.  Please include broken down average timeline on the wiki doc (ie. Build app takes x (with a list of build stages), Device farm takes x for x devices, Upload takes x etc etc)

**Comment by renevatium** [comment]
I'm confused. Of the last 9 builds: 5 were aborted, none got to the playstore and the succeeded builds show times of: 1 mins 33.596 secs, 40.734 secs, 5 mins 9.806 secs and 1 hrs 15 mins 49.874 secs respectively. Please could you explain the differences? Builds should be clean and working by now. The only issue should be upload to PlayStore.

**Comment by kearabiloe** [comment]
Yup, those were jenkins config/debug builds (no discovery tests and device farm)- the last build (58) is the working one,-it fails after trying to upload to Play
