### ISSUE TITLE
Test on range of devices

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-android#62]
On large box, testing should be faster. Check with the following devices and log times:
Samsung Galaxy S7
Sony Xperia Z5
Google Nexus X5/6P
LG G4/G5
HTC One A9/E8

**Comment by kearabiloe** [comment]
Tallied the results on the  deployment (Mobile) wiki.
Lg G4 fails :
Built-in Explorer Test failed: com.amazon.mas.avs.appexplorer.d.a: Error invoking executable: getprop
