### ISSUE TITLE
Screenshots in Device Farm

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-app-android#64]
Screenshots are great but not usable. Investigate configuration for specific screens (check live Proversity app for examples)

**Comment by kearabiloe** [comment]
Bummer! There's no option of  disabling screenshots capturing in BUILTIN_EXPLORER.

**Comment by renevatium** [comment]
From the [FAQ](): "If you use one of the supported automation frameworks, you are in full control and can decide when to take screenshots. Those screenshots are included in your reports automatically." Might need to edit/update the tests, but only taking 1 screenshot would be better than the default.

**Comment by renevatium** [comment]
Is there a lifetime on screenshots in Device Farm? ie Do they get deleted eventually?

**Comment by kearabiloe** [comment]
Alright, will look in to that. The lifetime is 30 days.

**Comment by renevatium** [comment]
Wont fix, moving to circle
