### ISSUE TITLE
Reduce the Jenkins build duration

### ISSUE THREAD

**Issue by kearabiloe** [proversity-org/edx-app-android#67]

**Comment by kearabiloe** [comment]
Android Sdk already installed globally. Removed the culprit gradle task: testProdReleaseUnitTestCoverage.

**Comment by renevatium** [comment]
Does that mean there are no tests running? That's kind of the point on CD.

**Comment by kearabiloe** [comment]
Alright, i'll reenable them and investigate further what's really going down inside the task. 
Future ref: [Build profile](http://52.34.215.134:8080/job/Jenkins-test-deploy.Android.Proversity/ws/build/reports/profile/profile-2016-04-19-11-05-13.html#tab3)

**Comment by renevatium** [comment]
Okay. Don't worry for now. Rather focus on the Kakfa projects.
